# Site settings
title: Hitch 
author: Spencer Hitchcock
avatar: "/img/avatar.png"
email: spencerhitch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Finnegans Wake, Motorcycles,
  RegExs, Zen, coffee, riddles,
  data visualization, composition,
  beer and lucid dreaming 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spencerhitch.github.io" # the base hostname & protocol for your site
twitter_username: spencerhitch 
github_username:  spencerhitch 

# Build settings
markdown: kramdown
